import {PersonajeModel} from "../models/personaje-model";

 export const listaPersonajes: PersonajeModel [] = [
    {nombre: 'Albedo',arma: 'Sword', rol: 'Support', elemeto: 'Geo', foto: 'assets/imagenes/Personaje_Albedo.png'},
    {nombre: 'Aloy',arma: 'Bow', rol: 'DPS', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Aloy.png'},
    {nombre: 'Amber',arma: 'Bow', rol: 'DPS', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Amber.png'},
    {nombre: 'Arataki Itto',arma: 'Claymore', rol: 'DPS', elemeto: 'Geo', foto: 'assets/imagenes/Personaje_Arataki_Itto.png'},
    {nombre: 'Barbara',arma: 'Catalyst', rol: 'Healer', elemeto: 'Hydro', foto: 'assets/imagenes/Personaje_Barbara.png'},
    {nombre: 'Beidou',arma: 'Claymore', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Beidou.png'},
    {nombre: 'Bennett',arma: 'Sword', rol: 'Healer', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Bennett.png'},
    {nombre: 'Chongyun',arma: 'Claymore', rol: 'Healer', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Chongyun.png'},
    {nombre: 'Diluc',arma: 'Claymore', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Diluc.png'},
    {nombre: 'Diona',arma: 'Bow', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Diona.png'},
    {nombre: 'Eula',arma: 'Claymore', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Eula.png'},
    {nombre: 'Fischl',arma: 'Bow', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Fischl.png'},
    {nombre: 'Ganyu',arma: 'Bow', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Ganyu.png'},
    {nombre: 'Gorou',arma: 'Bow', rol: 'Support', elemeto: 'Geo', foto: 'assets/imagenes/Personaje_Gorou.png'},
    {nombre: 'Hu Tao',arma: 'Polearm', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Hu_Tao.png'},
    {nombre: 'Jean',arma: 'Sword', rol: 'Support', elemeto: 'Anemo', foto: 'assets/imagenes/Personaje_Jean.png'},
    {nombre: 'Kaedehara Kazuha',arma: 'Sword', rol: 'Support', elemeto: 'Anemo', foto: 'assets/imagenes/Personaje_Kaedehara_Kazuha.png'},
    {nombre: 'Kaeya',arma: 'Sword', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Kaeya.png'},
    {nombre: 'Kamisato Ayaka',arma: 'Sword', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Kamisato_Ayaka.png'},
    {nombre: 'Kamisato Ayato',arma: 'Sword', rol: 'Support', elemeto: 'Hydro', foto: 'assets/imagenes/Personaje_Kamisato_Ayato.png'},
    {nombre: 'Keqing',arma: 'Sword', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Keching.png'},
    {nombre: 'Klee',arma: 'Catalyst', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Klee.png'},
    {nombre: 'Kujou Sara',arma: 'Bow', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Kujou_Sara.png'},
    {nombre: 'Lisa',arma: 'Catalyst', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Lisa.png'},
    {nombre: 'Mona',arma: 'Catalyst', rol: 'Support', elemeto: 'Hydro', foto: 'assets/imagenes/Personaje_Mona.png'},
    {nombre: 'Ningguang',arma: 'Catalyst', rol: 'Support', elemeto: 'Geo', foto: 'assets/imagenes/Personaje_Ninguang.png'},
    {nombre: 'Noelle',arma: 'Claymore', rol: 'Support', elemeto: 'Geo', foto: 'assets/imagenes/Personaje_Noelle.png'},
    {nombre: 'Qiqi',arma: 'Sword', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Qiqi.png'},
    {nombre: 'Raiden Shogun',arma: 'Polearm', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Shogun_Raiden.png'},
    {nombre: 'Razor',arma: 'Claymore', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Razor.png'},
    {nombre: 'Rosaria',arma: 'Polearm', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Rosaria.png'},
    {nombre: 'Sangonomiya Kokomi',arma: 'Catalyst', rol: 'Support', elemeto: 'Hydro', foto: 'assets/imagenes/Personaje_Sangonomiya_Kokomi.png'},
    {nombre: 'Sayu',arma: 'Claymore', rol: 'Support', elemeto: 'Anemo', foto: 'assets/imagenes/Personaje_Sayu.png'},
    {nombre: 'Shenhe',arma: 'Polearm', rol: 'Support', elemeto: 'Cryo', foto: 'assets/imagenes/Personaje_Shenhe.png'},
    {nombre: 'Sucrose',arma: 'Catalyst', rol: 'Support', elemeto: 'Anemo', foto: 'assets/imagenes/Personaje_Sacarosa.png'},
    {nombre: 'Tartaglia',arma: 'Bow', rol: 'Support', elemeto: 'Hydro', foto: 'assets/imagenes/Personaje_Tartaglia.png'},
    {nombre: 'Thoma',arma: 'Polearm', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Thoma.png'},
    {nombre: 'Traveler',arma: 'Sword', rol: 'Support', elemeto: '', foto: 'assets/imagenes/Personaje_Viajero.png'},
    {nombre: 'Venti',arma: 'Bow', rol: 'Support', elemeto: 'Anemo', foto: 'assets/imagenes/Personaje_Venti.png'},
    {nombre: 'Xiangling',arma: 'Polearm', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Xiangling.png'},
    {nombre: 'Xiao',arma: 'Polearm', rol: 'Support', elemeto: 'Anemo', foto: 'assets/imagenes/Personaje_Xiao.png'},
    {nombre: 'Xingqiu',arma: 'Sword', rol: 'Support', elemeto: 'Hydro', foto: 'assets/imagenes/Personaje_Xingchiu.png'},
    {nombre: 'Xinyan',arma: 'Claymore', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Xinyan.png'},
    {nombre: 'Yae Miko',arma: 'Catalyst', rol: 'Support', elemeto: 'Electro', foto: 'assets/imagenes/Personaje_Yae_Miko.png'},
    {nombre: 'Yanfei',arma: 'Sword', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Yanfei.png'},
    {nombre: 'Yelan',arma: 'Bow', rol: 'Support', elemeto: 'Hydro', foto: 'assets/imagenes/Personaje_Yelan.png'},
    {nombre: 'Yoimiya',arma: 'Bow', rol: 'Support', elemeto: 'Pyro', foto: 'assets/imagenes/Personaje_Yoimiya.png'},
    {nombre: 'Yun Jin',arma: 'Polearm', rol: 'Support', elemeto: 'Geo', foto: 'assets/imagenes/Personaje_Yun_Jin.png'},
    {nombre: 'Zhongli',arma: 'Polearm', rol: 'Support', elemeto: 'Geo', foto: 'assets/imagenes/Personaje_Zhongli.png'},
  ];

